Issue 92 weird app behavior
Saransh-cpp/BookRentApp-Chapter3 pull request #100
Opened 2021-12-16 14:18 UTC by mortal-ghost

## Program
- [X] CodePeak
- [ ] Script Winter of Code
- [ ] None

## Issue
Fixes #92 

## Description

Most of the issues seemed to be created by the _key.currentState.showSnackBar which is replaced by ScaffoldMessenger.of(context).showSnackBar.
Issue with confirming an order on dialog was because of the same reason as above but also needed the context of the underlying Scaffold rather than the dialog context which is declared as a new variable. 
The issues mentioned are resolved, I did not face any other issues.

## Type of change
You can write manually also

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] The app runs properly
- [X] I have performed a self-review of my own code
- [X] I have formatted and commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

2021-12-16 18:18 UTC, Saransh-cpp commented
Will review after #95 is merged.

2021-12-27 13:58 UTC, Saransh-cpp commented on pubspec.lock
>        name: async
Please revert back the changes in `pubspec.lock`

2021-12-31 14:07 UTC, Saransh-cpp commented
@mortal-ghost, please merge the master branch of my repository in this PR

2022-01-02 07:39 UTC, Saransh-cpp requested changes
Thanks, @mortal-ghost! Awesome work! This was a hard-to-spot bug. A few minor changes -
- There are other `SnackBar`s in `product_details.dart` that need these changes.
- You will need to do the same for the `Favourite` screen (again, just `SnackBar`s and probably the `context`), plus remove the `MaterialApp` parent widget from that screen.

2022-01-02 13:24 UTC, mortal-ghost commented
> Thanks, @mortal-ghost! Awesome work! This was a hard-to-spot bug. A few minor changes -
> 
> * There are other `SnackBar`s in `product_details.dart` that need these changes.
> * You will need to do the same for the `Favourite` screen (again, just `SnackBar`s and probably the `context`), plus remove the `MaterialApp` parent widget from that screen.

I have made the changes. On the product_details.dart, since the snackbar is displayed on the underlying Scaffold, Navigator pops the dialog first before displaying the snackbar. This is inline with the cart checkout.

2022-01-02 15:38 UTC, Saransh-cpp approved these changes
Thanks, @mortal-ghost! Looks good!

2022-01-02 15:38 UTC, merged