created a AboutUs screen-fixed issue#27
Saransh-cpp/BookRentApp-Chapter3 pull request #49
Opened 2021-12-06 10:09 UTC by Pranav108

In this PR , I created a AboutUs screen which shows us a brief info about this app and it's contributors along with the working link to their respective profile. I have to use http package in this issue which caused a lot version confliction with firebase packages.
So finally I also updated each dependency to their latest version keeping version confliction, null safety and other upcoming problems in mind. And during solving relative errors I also updated minSdkVersion and targetSdkVersion.
And I haven't attached this screens to any option yet because even after several attempt I didn't find anything on home screen to attach with.

2021-12-06 13:24 UTC, Saransh-cpp commented
@Pranav108, was there a template provided when you opened the PR, or was there none? (#44 should have had added a template but I'm not sure if it is working)

2021-12-06 13:58 UTC, Saransh-cpp requested changes
Thanks, @Pranav108! Looks very good overall. Here is a higher-level review. I'll look into it more soon!

2021-12-06 13:58 UTC, Saransh-cpp commented on android/app/build.gradle
> +    throw new FileNotFoundException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
Reason for this?

2021-12-06 13:58 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +      "BookRentApp application is specifically made for renting books.It displays collections of top selling books as well as the option to have your taste curated and matched with a book.Here custom
```suggestion
      "Chapter3 is an app specifically made for renting books. It displays collections of top-selling books as well as the option to have your taste curated and matched with a book. Here customers can filter and select books based on genre, after which placing immediate or deferred orders with the option to cancel.";
```

2021-12-06 13:58 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +    //final response = await http.get(Uri(host: contributorsAPIUrl));
```suggestion
```

2021-12-06 13:58 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +        //jsonContributors = json.decode(response.body) as List; //original
```suggestion
```

2021-12-06 13:58 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +        msg: "Failed to load Contributors from API",
```suggestion
        msg: "Failed to load Contributors.",
```

2021-12-06 13:58 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +                              "BOOK-RENT-APP",
```suggestion
                              "Chapter 3",
```

2021-12-06 13:58 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +                        "Presenting The Team",
```suggestion
                        "Presenting the Developers",
```

2021-12-06 13:58 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +                              (jsonContributors[index]["login"].toString() ==
I think you should also skip the `allcontributors` bot here, with my account.

2021-12-06 13:58 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +              //image: AssetImage('images/pranav.jpg'),
```suggestion
```

2021-12-06 14:29 UTC, Pranav108 commented on android/app/build.gradle
> +    throw new FileNotFoundException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
GradleExecption was showing in red(as deprecated I guess) , so I searched for its alternative and found FileNotFoundException as its latest alternative.

2021-12-06 14:34 UTC, Saransh-cpp commented on android/app/build.gradle
> +    throw new FileNotFoundException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
Oh oh, nice work!

2021-12-06 14:35 UTC, Pranav108 commented
> @Pranav108, was there a template provided when you opened the PR, or was there none? (#44 should have had added a template but I'm not sure if it is working)

I don't think so(or maybe few minutes before) because I was going through this repo whole day and must had noticed this kind of change.
And in hurry I forgot to give a last touch to the code. Should have removed those extra comments, I will take care of this things from next time.

2021-12-06 14:48 UTC, Pranav108 commented
I'm getting an option of 'resolve conversion' here, so I have to change it or you are improving it?
This is first time I'm going though this things, so don't know how to proceed.

2021-12-06 15:33 UTC, Saransh-cpp commented
> I'm getting an option of 'resolve conversion' here, so I have to change it or you are improving it? This is first time I'm going though this things, so don't know how to proceed.

These are some suggestions that should be implemented in this PR. You can do so directly from GitHub using the `Commit suggestion` button.

2021-12-06 16:39 UTC, Saransh-cpp commented
@Pranav108, can you merge the master branch of the main repository in this branch? Your branch is 20 commits behind, hence the home screen error (which has been fixed in the master branch).
![image](https://user-images.githubusercontent.com/74055102/144885765-76b074db-f044-419e-ae06-8e646e0f5fd7.png)

Let me know if you need any help:) !

2021-12-06 17:32 UTC, Pranav108 commented
> @Pranav108, can you merge the master branch of the main repository in this branch? Your branch is 20 commits behind, hence the home screen error (which has been fixed in the master branch). ![image](https://user-images.githubusercontent.com/74055102/144885765-76b074db-f044-419e-ae06-8e646e0f5fd7.png)
> 
> Let me know if you need any help:) !

I just did it, was that correct?

2021-12-06 17:52 UTC, Pranav108 reviewed
I think this should be fine now.

2021-12-06 20:52 UTC, Saransh-cpp requested changes
Thanks, @Pranav108! Awesome work! This is the final review -

2021-12-06 20:52 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +  String _about_this_app =
```suggestion
  String _aboutThisApp=
```

2021-12-06 20:52 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +        msg: "Failed to load Contributors.",
```suggestion
        msg: "Failed to load contributors.",
```

2021-12-06 20:52 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +    });
```suggestion
```

I don't think we need this. A constant timer isn't very useful while switching between screens.

2021-12-06 20:52 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +  bool _isLoading = true;
```suggestion
```

2021-12-06 20:52 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +          : SafeArea(
```suggestion
      body: SafeArea(
```

As we don't want the timer now.

2021-12-06 20:52 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +                                // color: Colors.orange[900],
```suggestion
```

2021-12-06 20:52 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +                            "ABOUT",
Could you add an `AppBar` saying "About" (with a default back arrow)? Then this about can be removed from here.

2021-12-06 20:52 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +                                fontSize: 25,
```suggestion
                                fontSize: 30,
```

2021-12-06 20:52 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +                          child: Text(_about_this_app),
```suggestion
                          child: Text(_aboutThisApp),
```

Can you also add center align here?

2021-12-06 20:52 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +      throw 'Could not launch $url';
We could add a snack bar here

2021-12-06 20:52 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +                    ),
```suggestion
```

On second thought, I think presenting the developers looks too weird😅

2021-12-07 05:12 UTC, Pranav108 commented on lib/Screens/AboutUs.dart
> +      throw 'Could not launch $url';
I have added a SnackBar but on multiple calling they are stored in a queue which cause each of them to appear one after another which is annoying ,  tried to fix it by using a flag variable but was unable to fix this. 
Will be if we tap on icon several times but the snackBar appear only once ,I searched about it but didn't find something relevant ,Can you please suggest me how to improve it?

2021-12-07 05:16 UTC, Pranav108 commented
Thanks for your suggestion, they really improved the view and code for screen a lot.
I also removed some redundant code as far I found them. Let me know about further improvement that need to be added.
This is the layout till now.
![AboutUsImprovementSection](https://user-images.githubusercontent.com/56934594/144970722-38ae5af1-0a7e-452c-ac3b-5f89b2923908.png)

2021-12-07 07:00 UTC, Saransh-cpp approved these changes
Thanks, @Pranav108! Looks great now! Merging!

2021-12-07 07:01 UTC, Saransh-cpp commented on lib/Screens/AboutUs.dart
> +      throw 'Could not launch $url';
I think we can leave it as it is.

2021-12-07 07:02 UTC, merged

2021-12-07 07:04 UTC, Saransh-cpp commented
@all-contributors please add @Pranav108 for code, design