Updated register.dart
Saransh-cpp/BookRentApp-Chapter3 pull request #51
Opened 2021-12-06 22:34 UTC by raviyadav17

## Issue
Fixes #(Mention the issue ID here)

<br>

## Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

<br>

## Type of change
You can write manually also

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change

<br>

## Screenshot
Screenshot of the fix if required.

<br>

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] The app runs properly
- [ ] I have performed a self-review of my own code
- [ ] I have formatted and commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2021-12-07 07:34 UTC, Saransh-cpp requested changes
Thanks, @raviyadav17! Looks good! Here is a high-level review, I'll look into this more soon!

2021-12-07 07:34 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +  Widget Template1(String hint , String error , Icon icon){
Give a meaningful name, please!

2021-12-07 07:34 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +  Widget Template2(String hint , String error ) {
Ditto!

2021-12-07 07:34 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +                      //Icons.remove_red_eye
```suggestion
```

2021-12-07 07:34 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +              // net ninja
```suggestion
```

2021-12-07 07:34 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +                        //Icons.remove_red_eye
```suggestion
```

2021-12-07 07:34 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +                        /* Container(
I think we can get rid of this now?

2021-12-07 08:20 UTC, raviyadav17 commented on lib/Screens/Register.dart
> +  Widget Template1(String hint , String error , Icon icon){
Done

2021-12-07 08:21 UTC, raviyadav17 commented on lib/Screens/Register.dart
> +  Widget Template2(String hint , String error ) {
Done

2021-12-07 08:21 UTC, raviyadav17 commented on lib/Screens/Register.dart
> +                      //Icons.remove_red_eye
Removed This

2021-12-07 08:21 UTC, raviyadav17 commented on lib/Screens/Register.dart
> +                        //Icons.remove_red_eye
Removed This

2021-12-07 08:21 UTC, raviyadav17 commented on lib/Screens/Register.dart
> +                        /* Container(
Removed This

2021-12-07 08:22 UTC, raviyadav17 commented on lib/Screens/Register.dart
> +              // net ninja
Removed It.

2021-12-07 19:36 UTC, Saransh-cpp commented
Thanks, @raviyadav17! This looks great! Can you merge in master before the final review? Your branch is 88 commits behind my repository's master branch. Let me know if you need any help!

2021-12-08 14:55 UTC, raviyadav17 commented
Successfully Merged Update Register.dart branch to master branch.

2021-12-08 15:51 UTC, Saransh-cpp requested changes
Awesome work! This is the final review, some minor naming issues, you can commit them directly from GitHub -

2021-12-08 15:51 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +  Widget InputFieldType2(String hint , String error ) {
```suggestion
  Widget PasswordField(String hint, String error ) {
```

2021-12-08 15:51 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +                        InputFieldType2("Enter Password", 'Enter a password 6+ chars long'),
```suggestion
                        PasswordField("Enter Password", 'Enter a password 6+ chars long'),
```

2021-12-08 15:51 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +                        InputFieldType2("Confirm Password", 'Enter a password 6+ chars long'),
```suggestion
                        PasswordField("Confirm Password", 'Enter a password 6+ chars long'),
```

2021-12-08 15:51 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +  Widget InputFieldType1(String hint , String error , Icon icon){
```suggestion
  Widget EmailAndNameField(String hint, String error, Icon icon){
```

2021-12-08 15:51 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +                        InputFieldType1("Enter Name" , 'Enter a name' , Icon(Icons.person)),
```suggestion
                        EmailAndNameField("Enter Name", 'Enter a name', Icon(Icons.person)),
```

2021-12-08 15:51 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +                        InputFieldType1("Enter Email" , 'Enter an email' , Icon(Icons.email)),
```suggestion
                        EmailAndNameField("Enter Email", 'Enter an email', Icon(Icons.email)),
```

2021-12-08 15:52 UTC, Saransh-cpp commented
@all-contributors please add @raviyadav17 for code, design.

2021-12-08 16:45 UTC, raviyadav17 commented on lib/Screens/Register.dart
> +  Widget InputFieldType2(String hint , String error ) {
done

2021-12-08 16:46 UTC, raviyadav17 commented on lib/Screens/Register.dart
> +                        InputFieldType2("Confirm Password", 'Enter a password 6+ chars long'),
Done

2021-12-08 16:46 UTC, raviyadav17 commented on lib/Screens/Register.dart
> +                        InputFieldType2("Enter Password", 'Enter a password 6+ chars long'),
Done

2021-12-08 16:46 UTC, raviyadav17 commented on lib/Screens/Register.dart
> +  Widget InputFieldType1(String hint , String error , Icon icon){
Done

2021-12-08 16:46 UTC, raviyadav17 commented on lib/Screens/Register.dart
> +                        InputFieldType1("Enter Name" , 'Enter a name' , Icon(Icons.person)),
Done

2021-12-08 16:47 UTC, raviyadav17 commented on lib/Screens/Register.dart
> +                        InputFieldType1("Enter Email" , 'Enter an email' , Icon(Icons.email)),
Done

2021-12-08 16:49 UTC, raviyadav17 commented
Successfully updated the minor issues

2021-12-08 18:35 UTC, Saransh-cpp commented
@raviyadav17 I don't see any new commits? Did you forget to push?

2021-12-08 18:51 UTC, raviyadav17 commented
> @raviyadav17 I don't see any new commits? Did you forget to push?

i updated in the master branch of my forked repo wait let me update it on other branch also

2021-12-08 18:56 UTC, Saransh-cpp approved these changes

2021-12-08 18:56 UTC, merged