Linting all files in lib except Screens
Saransh-cpp/BookRentApp-Chapter3 pull request #60
Opened 2021-12-07 10:32 UTC by Starkl7

## Issue
Fixes #04

<br>

## Description

Linted all files in lib, except Screens.
Mainly consisted of unused imports and incorrect camel case.

<br>

## Type of change

- Bug fix (non-breaking change which fixes an issue)

<br>

## Checklist:

-  My code follows the style guidelines of this project
-  The app runs properly
-  I have performed a self-review of my own code
-  I have formatted and commented my code, particularly in hard-to-understand areas
-  My changes generate no new warnings

2021-12-07 13:08 UTC, Saransh-cpp commented
@Starkl7, now that #57 is done, can you merge in master? Let me know if you need any help!

2021-12-07 16:44 UTC, Starkl7 commented
@Saransh-cpp Resolved the conflict, looks good?

2021-12-07 17:03 UTC, Saransh-cpp requested changes
Thanks, @Starkl7! Looks greats! Some comments below (major ones are associated with merging issues) -

2021-12-07 17:03 UTC, Saransh-cpp commented on lib/Widgets.dart
> +/* Widget _productImage(String picture) {
Is this function not being used anywhere?

2021-12-08 08:17 UTC, Starkl7 commented on lib/Widgets.dart
> +/* Widget _productImage(String picture) {
No, this func was unused. Instead of deleting, I though it would be better to comment it out.

2021-12-08 18:51 UTC, Saransh-cpp approved these changes
Thanks, @Starkl7! Awesome work! The tests are finally passing. I'll turn this into an easy issue (doesn't look like a `good first issue` as you went through all the files)

Could you resolve the conflicts? I will run the app tomorrow once and then merge!

2021-12-08 19:43 UTC, Starkl7 commented
@Saransh-cpp Thanks for the consideration. 
I resolved all the issues, should be good to go now.

2021-12-09 08:45 UTC, Starkl7 commented
Some new issues have popped up in Register.dart. I fixed the ones I could, a few I could not.
Pls look into that @Saransh-cpp.

2021-12-09 19:54 UTC, Starkl7 commented
@Saransh-cpp Some old code had been reintroduced in Register.dart. Probably messed up somewhere 😬 
Anyways took care of it so it should be cool now.

2021-12-10 08:56 UTC, Saransh-cpp reviewed
Awesome! Some minor comments below, also I'll put it up as moderate as this required a lot of work!

2021-12-10 08:56 UTC, Saransh-cpp commented on lib/Screens/product_details.dart
> +                    // appProvider.changeIsLoading();
Why was this commented?

2021-12-10 08:56 UTC, Saransh-cpp commented on lib/Screens/product_details.dart
> +              // appProvider.changeIsLoading();
Why was this commented?

2021-12-10 09:37 UTC, Starkl7 commented on lib/Screens/product_details.dart
> +                    // appProvider.changeIsLoading();
That was dead code. 
Above it is an if...else... and there in both blocks, whether if or else, there is a return statement. Therefore, the program execution would never reach this line.

2021-12-10 09:37 UTC, Starkl7 commented on lib/Screens/product_details.dart
> +              // appProvider.changeIsLoading();
Same reason as above... Dead (Unreachable) code

2021-12-10 13:07 UTC, Saransh-cpp commented on lib/Screens/product_details.dart
> +                    // appProvider.changeIsLoading();
Oh oh, didn't see the code above, thanks!

2021-12-10 13:07 UTC, Saransh-cpp commented
@Starkl7, you are only a part of SWoC right?

2021-12-10 13:09 UTC, Saransh-cpp commented
@all-contributors please add @Starkl7 for code

2021-12-10 13:10 UTC, merged

2021-12-10 17:18 UTC, Starkl7 commented
@Saransh-cpp Thanks for putting it up as moderate. It felt great contributing to this project. 😄
Yes, I am participating in SWOC only.