Fixed home.dart
Saransh-cpp/BookRentApp-Chapter3 pull request #76
Opened 2021-12-10 12:55 UTC by raviyadav17

## Issue
Fixes #68 

## Description

I have updated a little part of the code and fixed the error.

## Type of change

-  Bug fix (non-breaking change which fixes an issue)

## Screenshot
![Screenshot_1639140528](https://user-images.githubusercontent.com/86602971/145577126-17f77bff-8c3c-45e3-a086-89c8411f76bf.png)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] The app runs properly
- [ ] I have performed a self-review of my own code
- [ ] I have formatted and commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

I am member of Codepeak 
thank you

2021-12-10 13:08 UTC, Saransh-cpp commented
@raviyadav17, please merge master of my repository

2021-12-10 13:19 UTC, raviyadav17 commented
I have merged the changes to the master branch of my repository . I don't know how to merge to your master branch.

2021-12-10 13:22 UTC, Saransh-cpp commented
@raviyadav17, you don't have to merge into my master branch. Merge my master branch into your PR's branch. If you are having any issues then please let me know the output of `git remote -v`.

2021-12-10 13:36 UTC, raviyadav17 commented
Can you tell how to Merge my master branch into your PR's branch??

2021-12-10 15:50 UTC, Saransh-cpp commented
What does `git remote -v` give you?

2021-12-10 21:39 UTC, raviyadav17 commented
origin  https://github.com/raviyadav17/BookRentApp-Chapter3.git (fetch)
origin  https://github.com/raviyadav17/BookRentApp-Chapter3.git (push)

2021-12-11 06:31 UTC, Saransh-cpp commented
Make sure you are on your `Fixed-Home.dart` branch, execute the following -
```
git remote add upstream https://github.com/Saransh-cpp/BookRentApp-Chapter3
git pull upstream master
```
This will add a new remote named upstream which will point to my repository (you can check using `git remote -v`). The second command will merge my master branch to your current branch.

After this, resolve the conflicts and push the code.

2021-12-11 08:57 UTC, raviyadav17 commented
**Done**
origin  https://github.com/raviyadav17/BookRentApp-Chapter3.git (fetch)
origin  https://github.com/raviyadav17/BookRentApp-Chapter3.git (push)
upstream        https://github.com/Saransh-cpp/BookRentApp-Chapter3 (fetch)
upstream        https://github.com/Saransh-cpp/BookRentApp-Chapter3 (push)

**But** 
CONFLICT (content): Merge conflict in lib/Screens/Register.dart
Automatic merge failed; fix conflicts and then commit the result.

2021-12-11 14:12 UTC, Saransh-cpp commented
Yes, you have to fix these conflicts in your code manually, in the file `lib/Screens/Register.dart`.

2021-12-11 16:03 UTC, raviyadav17 commented
> Yes, you have to fix these conflicts in your code manually, in the file `lib/Screens/Register.dart`.

I am trying but lint-check is failing everytime

2021-12-11 16:13 UTC, Saransh-cpp requested changes
@raviyadav17, I have listed some of the changes below

There are changes in files other than `Home.dart` (there shouldn't be any as this PR is only concerned with `Home.dart`). Hence you should revert all of them back, manually.

The linting issue should be solved once all the other files are reverted to their initial state.

Let me know if you face any issues! :)

2021-12-11 16:13 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +import 'package:firebase_database/firebase_database.dart';
```suggestion
// import 'package:firebase_database/firebase_database.dart';
```

2021-12-11 16:13 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +import 'dart:math';
```suggestion
// import 'dart:math';
```

2021-12-11 16:13 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +import 'dart:io';
```suggestion
// import 'package:test_app/Utility/auth.dart';
// import 'package:test_app/main.dart';
// import 'dart:io';
```

2021-12-11 16:13 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +import 'package:firebase_storage/firebase_storage.dart';
```suggestion
// import 'package:image_picker/image_picker.dart';
// import 'package:shared_preferences/shared_preferences.dart';
// import 'package:test_app/Screens/LoginPage.dart';
// import 'package:firebase_storage/firebase_storage.dart';
```

2021-12-11 16:13 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +  final _key = GlobalKey<ScaffoldState>();
```suggestion
  final _key = GlobalKey<ScaffoldMessengerState>();
```

2021-12-11 16:13 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +  String cpassword ='';
```suggestion
  String cpassword = '';
```

2021-12-11 16:13 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +
```suggestion
```

2021-12-11 16:13 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +  File _imageFile;
```suggestion
```

2021-12-11 16:13 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +        .width;
```suggestion
  Widget emailAndNameField(String hint, String error, Icon icon) {
    double _screenWidth = MediaQuery.of(context).size.width;
```

2021-12-11 16:13 UTC, Saransh-cpp commented on lib/Screens/Register.dart
> +          width: _screenWidth/1.08,
```suggestion
          width: _screenWidth / 1.08,
```

2021-12-11 17:25 UTC, raviyadav17 commented
Still lint check is failed after reverting changes

2021-12-12 13:52 UTC, Saransh-cpp commented
@raviyadav17, I pointed out only a few issues. You have to revert back all the files to their initial state, except `Home.dart`.

I see 3 files changes in this PR, but this PR should only change the `Home.dart` file -

![image](https://user-images.githubusercontent.com/74055102/145715114-f2021a98-e863-416f-ac4f-74022efb5ef0.png)

2021-12-13 20:03 UTC, closed without merging