Improved YourCart section with new features
Saransh-cpp/BookRentApp-Chapter3 pull request #83
Opened 2021-12-11 10:32 UTC by Pranav108

## Program
- [x] CodePeak
- [ ] Script Winter of Code
- [ ] None

## Issue
Fixes #74

## Description
If cart will be empty then UI will be a bit different and on clicking on `Add Item` user will be referred to Recommendation screen and if there will be any product in cart then we can see the option to purchase them.
Improved the designing of cart, button, appbar, etc.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change

## Screenshot
Screenshot of the fix if required.
<img src="https://user-images.githubusercontent.com/56934594/145673129-8e952366-a5c3-4ab9-9510-a696153c997c.png" alt="drawing" width="300"/><img src="https://user-images.githubusercontent.com/56934594/145673084-b074e270-a203-4e5d-a79f-27202f141796.png" alt="drawing" width="300"/>

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] The app runs properly
- [x] I have performed a self-review of my own code
- [x] I have formatted and commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-12-11 14:33 UTC, Saransh-cpp commented
@Pranav108 can you also add screenshots for all the dialogue boxes?

2021-12-11 15:12 UTC, Pranav108 commented
I have Updated the screenShot in PR , that's the only dialog box I found on this screen . There was one more for the situation for cart to be empty but I removed that Instead of that now user will be referred to recommendation section on pression on `add item`.

2021-12-12 13:43 UTC, Saransh-cpp requested changes
@Pranav108, a quick review -

1. Please merge master and update your fork.
2. AppBar's color and the screen's color should be the same.
3. Please close the ad when a user switches to another screen.

<img src="https://user-images.githubusercontent.com/74055102/145714726-6442e3d9-0db7-4a23-bb22-5abc53fbb4db.png" height=500/>

2021-12-12 22:45 UTC, Pranav108 commented
I am unable to merge you master branch with my local branch , can just update the code for now?

2021-12-13 10:15 UTC, Pranav108 commented
> @Pranav108, a quick review -
> 
> 1. Please merge master and update your fork.
> 2. AppBar's color and the screen's color should be the same.
> 3. Please close the ad when a user switches to another screen.
> 
Now AppBar's color and the screen's color are be the same and ad will close when user switches to another screen. 
<img src="https://user-images.githubusercontent.com/56934594/145793313-0b8cef55-4555-4e7f-8f65-43c84fbfeea5.png" alt="drawing" width="200"/>

2021-12-15 14:46 UTC, Pranav108 commented
@Saransh-cpp do I need to add something more for this PR?

2021-12-15 17:02 UTC, Saransh-cpp commented
Please resolve conflicts, honestly due to #92, it is getting a bit tough to review this PR but I will review it once the conflicts are resolved.

2021-12-16 19:14 UTC, Saransh-cpp requested changes
@Pranav108, apologies for taking forever to review. I am seeing an error on pressing the Add Item button -
```
The following assertion was thrown while handling a gesture:
'package:firebase_admob/firebase_admob.dart': Failed assertion: line 253 pos 12: '_allAds[id] != null': is not true.

When the exception was thrown, this was the stack: 
#2      MobileAd.dispose (package:firebase_admob/firebase_admob.dart:253:12)
#3      _YourOrdersState.build.<anonymous closure> (package:test_app/Screens/YourOrders.dart:284:39)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
#9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:444:20)
#11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#20     _invoke1 (dart:ui/hooks.dart:185:10)
#21     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#22     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
```
I think you will have to check if the ad is even active and then dispose it off.

2021-12-17 08:02 UTC, Pranav108 commented
Now I am unable to run the code ,getting something like : 
`Your Flutter application is created using an older version of the Android embedding.`
` It is being deprecated in favor of Android embedding v2.`
So for running should I migrate it or ignore it for now?

2021-12-19 06:45 UTC, Saransh-cpp commented
@Pranav108, you can work on this now.

2021-12-19 09:38 UTC, Pranav108 commented
> @Pranav108, apologies for taking forever to review. I am seeing an error on pressing the Add Item button -
> 
> ```
> The following assertion was thrown while handling a gesture:
> 'package:firebase_admob/firebase_admob.dart': Failed assertion: line 253 pos 12: '_allAds[id] != null': is not true.
> 
> When the exception was thrown, this was the stack: 
> #2      MobileAd.dispose (package:firebase_admob/firebase_admob.dart:253:12)
> #3      _YourOrdersState.build.<anonymous closure> (package:test_app/Screens/YourOrders.dart:284:39)
> #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
> #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
> #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
> #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
> #8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
> #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
> #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:444:20)
> #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
> #12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
> #13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
> #14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
> #15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
> #16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
> #20     _invoke1 (dart:ui/hooks.dart:185:10)
> #21     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
> #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
> ```
> 
> I think you will have to check if the ad is even active and then dispose it off.

Yeah I found this few days ago but app didn't crashes so I think we are okay with this.
With the existing `firebase_admob` package we can now fix this error with only one solution which is a small change in `package:firebase_admob/firebase_admob.dart`  file (with another warning ,because this file is read only), which may not be a good idea. 
And the second permanent solution will we use of `google_mobile_ads` because `firebase_admob` is deprecated.
![image](https://user-images.githubusercontent.com/56934594/146670008-1adb6889-eb0d-42f4-8858-a4ca5d252480.png)
I tried to implement `google_mobile_ads` package but got confused with different appID at several places.
So for ad improvement ,another issue will be effecient and I would love to give that another try.

2021-12-27 13:59 UTC, Saransh-cpp commented
@Pranav108 can you create a new issue for this?

2021-12-27 16:49 UTC, Pranav108 commented
> @Pranav108 can you create a new issue for this?

Okay , I have raised an issue for that.
And apart from the current banner ads , in the new package we can also implement a optional full screen ads for few seconds. Should I ask to implement this extra feature in issue.

2021-12-28 07:24 UTC, Saransh-cpp commented
> And apart from the current banner ads , in the new package we can also implement a optional full screen ads for few seconds. Should I ask to implement this extra feature in issue.

Yes, a new issue!

2021-12-28 19:25 UTC, Saransh-cpp commented
@Pranav108 can you merge master?

2021-12-29 04:12 UTC, Pranav108 commented
My master into yours? No , coz I have a different branch for this issue.

2021-12-29 20:44 UTC, Saransh-cpp commented
My master into your current branch

2021-12-30 13:30 UTC, Pranav108 commented
> My master into your current branch

yeah, I can merge there is no conflict now ,should I ?

2021-12-31 14:08 UTC, Saransh-cpp commented
> yeah, I can merge there is no conflict now ,should I ?

Yes, your branch is 22 commits behind, would be difficult to review.

2022-01-02 15:42 UTC, Saransh-cpp commented
@Pranav108, I am really sorry for the delay but now that the bug associated with `YourOrdrs.dart` has been solved, can you merge my master branch again? I'll review as soon as you merge!

2022-01-02 17:14 UTC, Pranav108 commented
> @Pranav108, I am really sorry for the delay but now that the bug associated with `YourOrdrs.dart` has been solved, can you merge my master branch again? I'll review as soon as you merge!

It's okay bro, I've merged with your master branch.

2022-01-02 19:05 UTC, Saransh-cpp requested changes
Thanks, @Pranav108! Awesome work! The ad still gives the same error but I think it would be taken care of in #111. A couple of minor comments below -

2022-01-02 19:05 UTC, Saransh-cpp commented on lib/Screens/YourOrders.dart
>              elevation: 1,
```suggestion
            elevation: 0,
```

2022-01-02 19:05 UTC, Saransh-cpp commented on lib/Screens/YourOrders.dart
> +                          'images/emptycart.png',
This gives me the following error -

<img src="https://user-images.githubusercontent.com/74055102/147886508-b35085a0-9af0-4437-9505-a528b82b68b9.png" height=500/>

I think you forgot to add the file in `pubspec.yaml`?

2022-01-02 19:31 UTC, Saransh-cpp approved these changes

2022-01-02 19:46 UTC, merged

2022-01-02 19:47 UTC, Pranav108 commented
Thanks bro🤩