Issue 94 signing issues
Saransh-cpp/BookRentApp-Chapter3 pull request #95
Opened 2021-12-14 17:06 UTC by mortal-ghost

## Program
- [X] CodePeak
- [ ] Script Winter of Code
- [ ] None

## Issue
Fixes #94 

## Description
No snackbar on signing in was caused by a duplicated Scaffold in lib/Screens/LoginPage.dart which was removed.
Sign out issue was seemingly caused by Navigator pushing replacement onto nothing as when we signed in the login screen/register screen was automatically changed to home screen by the providers. (Not sure though, nothing else seemed wrong). Both lib/Screens/LoginPage.dart and lib/Screens/Register.dart are changed.

## Type of change
You can write manually also

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] The app runs properly
- [X] I have performed a self-review of my own code
- [X] I have formatted and commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

2021-12-14 20:04 UTC, Saransh-cpp requested changes
@mortal-ghost please merge the master branch of my repository

2021-12-14 20:20 UTC, mortal-ghost commented
Is it done?

2021-12-15 14:16 UTC, Saransh-cpp requested changes

2021-12-15 14:16 UTC, Saransh-cpp commented on lib/main.dart
>        case Status.Authenticating:
@mortal-ghost, I think the main issue was with a missing statement in `case Status.Unauthenticated:`? Why is `Splash` screen removed now?

2021-12-15 14:16 UTC, Saransh-cpp commented on lib/Screens/LoginPage.dart
> -                                            builder: (c) => NavBar()));
Shouldn't the `NavBar` screen be pushed when a user successfully authenticates?

2021-12-15 14:44 UTC, mortal-ghost commented on lib/main.dart
>        case Status.Authenticating:
I tried adding the login page on status.unauthenticated , the error persisted. It was also like this when the app functioned correctly. I think the problem was with the navigator, the NavBar was pushed as replacement when we did not really need to push anything as providers will listen to the authentication changes and return NavBar() in ScreensController. The navigator was actually pushing NavBar() onto the ScreensController widgets. That's why when we logged out, nothing happened because there was nothing to listen to the changes.

2021-12-16 17:59 UTC, Saransh-cpp requested changes
Thanks, @mortal-ghost! Great work! A few points -

1. Putting `LoginPage` in the `Uninitialized` case means that when the app is not initialized, the login page will be displayed. Let's say a user is already logged in and they open their app again, in this scenario the user will see the splash screen first, the logging page after that, and the home screen after that. We don't want this.
2. In the `Unauthenticated` case, the `LoginPage` should be displayed again as the user is not authenticated. Right now the login page is still displayed as the `case Status.Unauthenticated:` does not have a return or a break statement (fall through error).
3. While running your branch, I encountered an error with the `snackbar`. It is not being displayed on the `LoginPage` if the signing-in fails. I was able to fix this locally, let me know if you need the quick solution :)

2021-12-16 17:59 UTC, Saransh-cpp commented on lib/main.dart
> +        return LoginPage();
```suggestion
        return Splash();
```

2021-12-16 17:59 UTC, Saransh-cpp commented on lib/main.dart
>        case Status.Unauthenticated:
Add `return LoginPage();` below this line

2021-12-19 14:13 UTC, mortal-ghost commented on lib/main.dart
> +        return LoginPage();
I got the *1 point, thank you very much.
*2 I will do that in a moment.
*3 This was one of the two issues I fixed. When I run the app, snackbar works correctly. I will check it again though.

2021-12-27 13:57 UTC, Saransh-cpp requested changes
Thanks, @mortal-ghost! Looks awesome now! A few minor changes -

2021-12-27 13:57 UTC, Saransh-cpp commented on nano.save
> +SizedBox(
We don't need this file, I think you added this by mistake

2021-12-27 13:57 UTC, Saransh-cpp commented on pubspec.lock
>        name: async
Please revert back the changes in `pubspec.lock`

2021-12-30 05:25 UTC, mortal-ghost commented on nano.save
> +SizedBox(
Yeah, I don't know where this came from, I have deleted it

2021-12-30 11:18 UTC, Saransh-cpp approved these changes
Thanks, @mortal-ghost! Looks awesome!

2021-12-30 11:18 UTC, merged